### ISSUE TITLE
README seems out of sync with repo

### ISSUE THREAD

**Issue by vreuter** [databio/dockerfiles#2]
It looks like there's a lot more content in the repo and some of the naming / organization has changed from the last README update.

**Comment by nsheff** [comment]
probably true... I need to clean this up...

thanks for the ping

**Comment by nsheff** [comment]
Here's another earlier version: https://github.com/nsheff/docker

I'm in process of uniting these into one cohesive process. should document things much better

**Comment by nsheff** [comment]
Hey, I updated this, it should be much more approachable now. I cleaned up the whole system and it's easier to understand, and everything works again. thanks for point this out.
